name: Test Student Grading App On Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test-App-On-Windows:

    runs-on: windows-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: maven

      - name: compile project
        run: mvn compile

      - name: Build and Run Tests
        run: mvn test --batch-mode --fail-at-end

      - name: Publish Test Report
        if: always()
        uses: ScaCap/action-surefire-report@v1.8.0
        with:
          path: target/surefire-reports
          report_always: true





